name: Secure Remote Command Execution

on:
  push:
    branches:
      - main

jobs:
  execute-command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send API Request
        env:
          EXECUTOR_TOKEN: ${{ secrets.REMOTE_EXECUTOR_TOKEN }}
          TARGET_URL: ${{ secrets.URL }}
        run: |
          # 定义重试策略
          max_retries=3
          retry_delay=5
          attempt=0
          success=false
          response=""
          
          while [ $attempt -lt $max_retries ] && [ "$success" = false ]; do
            echo "Attempt $((attempt+1)) of $max_retries"
            
            # 修复后的curl命令（关键修改点）
            response=$(curl -s -w "%{http_code}" -X POST \
              -H "Content-Type: application/json" \
              -H "Authorization: $EXECUTOR_TOKEN" \
              -d "{\"command\": \"auto-pull-homepage\"}" \
              "$TARGET_URL")
            
            # 分离状态码和响应体
            http_code=${response: -3}
            body=${response:0:-3}
            
            # 记录调试信息
            echo "::debug::Status Code: $http_code"
            echo "::debug::Response Body: $body"
            
            if [ "$http_code" -eq 200 ]; then
              echo "Command executed successfully"
              success=true
            else
              echo "Request failed (HTTP $http_code). Retrying in $retry_delay seconds..."
              sleep $retry_delay
            fi
          done

          # 最终状态检查
          if [ "$success" = false ]; then
            echo "Deployment failed after $max_retries attempts"
            exit 1
          fi
